theme = "MyTheme"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
rulers = [80, 100]
bufferline = "multiple"
color-modes = true
shell = [
  "powershell.exe", 
  "-NoProfile",
  "-Command",
]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]
idle-timeout = 0
completion-trigger-len = 1

[editor.cursor-shape]
normal = "block"
insert = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-signature-help-docs = false


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'