[[language]]
name = "markdown"
language-server = { command = "C:\\Users\\Chris\\lsp\\ltex-ls-15.2.1-alpha.1.nightly.2022-12-08\\bin\\ltex-ls.bat" }
file-types = ["md"]
scope = "source.markdown"
roots = []  